name: GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:

      - name: GitHub Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-overview.svg

          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: neerajsutha973r

          base: repositories, metadata

          plugin_languages: yes
          plugin_languages_limit: 5
          plugin_languages_details: percentage
          plugin_languages_sections: most-used

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          plugin_stars: yes
          plugin_stars_limit: 3

          config_display: small

          extras_css: |
            h2 {
              font-size: 18px !important;
            }

            h3 {
              font-size: 15px !important;
            }

            text {
              font-size: 12px !important;
            }

          optimize: yes

      - name: Contribution Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-calendar.svg

          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: neerajsutha973r

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          config_display: small

          extras_css: |
            h2 {
              font-size: 18px !important;
            }

            h3 {
              font-size: 15px !important;
            }

            text {
              font-size: 12px !important;
            }

          optimize: yes
